Updated Entities URLs to fix FTBFS in offline environment.
 This commit set canonical URLs for Entities as they refer to themselves.

 Incorrect URLs cause FTBFS in offline build environment even when
 "w3c-sgml-lib" package is installed:

~~~~
Error: Could not parse document:
 connection refused ..//C/gnumeric.xml:51:  I/O  warning :  failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/ent/isopub.ent"
   %isopub;
           ^
  %isopub;
          ^
 connection refused ..//C/gnumeric.xml:56:  I/O  warning :  failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/ent/isonum.ent"
   %isonum;
           ^
  %isonum;
          ^
 connection refused ..//C/gnumeric.xml:61:  I/O  warning :  failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/ent/isogrk1.ent"
   %isogrk1;
            ^
~~~~

Signed-off-by: Dmitry Smirnov <onlyjob@member.fsf.org>